# Generated by Django 4.2.7 on 2026-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_llm_module_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_region',
            field=models.CharField(default='in', max_length=8),
        ),
    ]
