# Generated by Django 4.2.7 on 2026-08-07 21:02

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_data_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_region',
            field=models.CharField(default=apps.users.models._default_data_region, max_length=8),
        ),
    ]
