# Generated by Django 4.2.7 on 2026-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0075_waitlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsendquota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='meta_template_name',
            field=models.CharField(blank=True, help_text='Exact template name in Meta Business Manager (only relevant when meta_approved=True)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
