# Generated by Django 4.2.7 on 2026-05-08 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0076_alter_hostsendquota_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='Client-supplied idempotency key. Same request_id within 60s reuses the prior result.', max_length=64)),
                ('operation', models.CharField(choices=[('vision', 'Vision'), ('text', 'Text')], max_length=32)),
                ('provider', models.CharField(default='anthropic', max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cache_hit', models.BooleanField(default=False, help_text='True when the call was served from cache and incurred no provider cost.')),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary debug context: card_url, event_type, attempt #, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Superuser who triggered the call. Null only if the call was system-initiated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Usage Ledger Entry',
                'verbose_name_plural': 'LLM Usage Ledger Entries',
                'db_table': 'llm_usage_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='llm_usage_user_time_idx'), models.Index(fields=['created_at', 'success'], name='llm_usage_time_success_idx'), models.Index(fields=['request_id', 'created_at'], name='llm_usage_request_idx')],
            },
        ),
    ]
