# Generated by Django 4.2.7 on 2026-05-12 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_llm_platform_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmplatformsettings',
            name='daily_cost_cap_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Global daily spend cap in USD (ledger-based, all users).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='llmplatformsettings',
            name='monthly_cost_cap_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Global monthly spend cap in USD (ledger-based, all users).', max_digits=12),
        ),
    ]
