# Generated by Django 4.2.7 on 2026-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_alter_event_has_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data_region',
            field=models.CharField(default='in', max_length=8),
        ),
    ]
