# Generated by Django 4.2.7 on 2026-08-07 21:02

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_event_data_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_region',
            field=models.CharField(default=apps.events.models._default_data_region, max_length=8),
        ),
    ]
