# Generated by Django 4.2.7 on 2026-08-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_image_tile_becomes_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Invitation page configuration: appearance plus an ordered list of tiles'),
        ),
        migrations.AlterField(
            model_name='invitepagelayout',
            name='config',
            field=models.JSONField(default=dict, help_text='Full InviteConfig: tiles, customColors, customFonts, texture, etc.'),
        ),
    ]
