# Generated by Django 4.2.7 on 2026-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0104_drop_map_height'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitepageview',
            name='invite_views_unique_guest_event_time',
        ),
        migrations.AddField(
            model_name='invitepageview',
            name='view_bucket',
            field=models.DateTimeField(blank=True, help_text='Start of the dedupe window this view falls in. Carries the unique constraint so repeat requests within the window collapse into one row. Null on rows recorded before de-duplication existed.', null=True),
        ),
        migrations.AddConstraint(
            model_name='invitepageview',
            constraint=models.UniqueConstraint(fields=('guest', 'event', 'view_bucket'), name='invite_views_unique_guest_event_bucket'),
        ),
    ]
