# Generated by Django 4.2.7 on 2026-09-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_invite_view_dedupe_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_channel', models.CharField(choices=[('qr', 'QR Code'), ('link', 'Web Link'), ('manual', 'Manual')], default='link', max_length=20)),
                ('viewed_at', models.DateTimeField(help_text='When the guest opened the catalog')),
                ('view_bucket', models.DateTimeField(blank=True, help_text='Start of the dedupe window this view falls in; carries the unique constraint.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_views', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_views', to='events.guest')),
            ],
            options={
                'db_table': 'catalog_page_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['event', '-viewed_at'], name='catalog_views_event_idx'), models.Index(fields=['guest', '-viewed_at'], name='catalog_views_guest_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogpageview',
            constraint=models.UniqueConstraint(fields=('guest', 'event', 'view_bucket'), name='catalog_views_unique_guest_event_bucket'),
        ),
    ]
