# Generated by Django 4.2.7 on 2026-09-28 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0111_invite_page_layout_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('left', 'Left')], default='pending', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohosts', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohosted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_cohosts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='event_cohost_user_status_idx'), models.Index(fields=['event', 'status'], name='event_cohost_event_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventcohost',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='event_cohost_unique_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='eventcohost',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('event', 'invited_email'), name='event_cohost_unique_active_email_per_event'),
        ),
    ]
