# Generated by Django 4.2.7 on 2026-09-28 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0112_event_cohosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=32)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_versions', to='events.event')),
                ('saved_by', models.ForeignKey(blank=True, help_text='Who saved this version. Kept if the account is later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_design_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='design_version_event_idx')],
            },
        ),
    ]
