# Generated by Django 4.2.7 on 2026-10-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0115_cohost_notifications_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcohost',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
