# Generated by Django 4.2.7 on 2026-10-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0117_dress_code_into_good_to_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='good_to_know',
            field=models.JSONField(blank=True, default=list, help_text="This sub-event's answers to what guests ask - dress code, stay, parking, food, contact. List of {id, kind, text, url?}; see apps/events/good_to_know.py."),
        ),
    ]
