# Generated by Django 4.2.7 on 2026-10-08 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0119_add_meetup_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancel_note',
            field=models.TextField(blank=True, default='', help_text="The host's message to guests about the cancellation."),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Set when the host cancels: RSVP and gifts close at once.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='catalog_closed_at',
            field=models.DateTimeField(blank=True, help_text='Host closed gifts early. Clearing it reopens them, up to the normal window.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='catalog_days_after_end',
            field=models.PositiveIntegerField(blank=True, help_text='Gifts stay open this many days after the end. Blank: the platform default.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Stored copy of lifecycle.compute_ends_at for queries: start of the day after the last day, in the event's zone. Null: undated, or a series with no end. Kept in sync on save.", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host_warned_link_off_at',
            field=models.DateTimeField(blank=True, help_text='When the host was warned the link is closing. The link never goes off before this plus the notice period.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_active_until',
            field=models.DateField(blank=True, help_text="Staff override: keep the link working through this day (event's zone).", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_days_after_end',
            field=models.PositiveIntegerField(blank=True, help_text='The link stops working this many days after the end. Blank: the platform default.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_exdates',
            field=models.JSONField(blank=True, default=list, help_text='Series dates the host skipped (ISO dates).'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rrule',
            field=models.CharField(blank=True, default='', help_text='RFC 5545 RRULE for a repeating series (e.g. FREQ=WEEKLY;BYDAY=SU), anchored on `date`. Empty: one-off.', max_length=255),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Retired: replaced by the event lifecycle (apps/events/lifecycle.py). Not read.', null=True),
        ),
        migrations.CreateModel(
            name='EventLifecycleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('happening', 'Started'), ('ended', 'Ended'), ('catalog_closed', 'Gifts closed'), ('archived', 'Link went off'), ('warned_catalog', 'Host warned: gifts closing'), ('warned_link', 'Host warned: link going off'), ('ended_summary', 'Host sent the after-event summary')], max_length=32)),
                ('for_moment', models.DateTimeField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_transitions', to='events.event')),
            ],
            options={
                'db_table': 'event_lifecycle_transitions',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='EventLifecycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_days_after_end', models.PositiveIntegerField(default=30, help_text='The invite link stops working this many days after the event ends.')),
                ('catalog_days_after_end', models.PositiveIntegerField(default=30, help_text='Gifts stay open this many days after the event ends.')),
                ('warn_days_before', models.PositiveIntegerField(default=7, help_text='Hosts are warned this many days before gifts close or the link goes off. The link never goes off sooner than this after the warning.')),
                ('enforce_link_off', models.BooleanField(default=False, help_text='Master switch for links going off. Leave off until the lifecycle job is confirmed running and its warning emails arrive; while off, every link stays active.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Lifecycle Settings',
                'verbose_name_plural': 'Event Lifecycle Settings',
                'db_table': 'event_lifecycle_settings',
            },
        ),
        migrations.CreateModel(
            name='EventLifecycleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('close_catalog', 'Closed gifts'), ('reopen_catalog', 'Reopened gifts'), ('cancel', 'Cancelled event'), ('uncancel', 'Restored cancelled event'), ('link_active_until', 'Changed link override'), ('windows', 'Changed gift/link days'), ('series', 'Changed repeat rule')], max_length=32)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_overrides', to='events.event')),
            ],
            options={
                'db_table': 'event_lifecycle_overrides',
                'ordering': ['-at'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventlifecycletransition',
            constraint=models.UniqueConstraint(fields=('event', 'kind', 'for_moment'), name='uniq_lifecycle_transition'),
        ),
    ]
