"""
Regenerate frontend/lib/countryTimezones.ts from IANA's zone.tab.

    docker compose exec -T backend python - < frontend/scripts/generate_country_timezones.py \
        > frontend/lib/countryTimezones.ts

Reads the `tzdata` package the backend already pins, so the frontend's list
matches the zones the backend accepts. Rerun after bumping tzdata.
"""
import importlib.resources
import json

import tzdata

rows = (importlib.resources.files('tzdata') / 'zoneinfo' / 'zone.tab').read_text().splitlines()
zones = {}
for line in rows:
    if not line or line.startswith('#'):
        continue
    country, _coords, zone = line.split('\t')[:3]
    zones.setdefault(country, []).append(zone)

body = ',\n'.join(f'  {country}: {json.dumps(z)}' for country, z in sorted(zones.items()))
print(f'''/**
 * Each country's IANA time zones, from zone.tab (tzdata {tzdata.IANA_VERSION}).
 * Generated by scripts/generate_country_timezones.py - do not edit by hand.
 *
 * Used when city search is unavailable: a country with one zone gives the
 * event its time zone outright; one with several asks the host which.
 */
export const COUNTRY_TIMEZONES: Record<string, readonly string[]> = {{
{body},
}}
''')
