# Generated by Django 4.2.7 on 2026-08-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0095_event_data_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('access', 'Access'), ('export', 'Export'), ('erase', 'Erase'), ('anonymize', 'Anonymize'), ('login', 'Login'), ('permission_change', 'Permission change'), ('notify', 'Notify')], max_length=32)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('subject_ref', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'privacy_audit_event',
                'indexes': [models.Index(fields=['action', 'created_at'], name='privacy_aud_action_872c1e_idx'), models.Index(fields=['target_model', 'target_id'], name='privacy_aud_target__a61113_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=16)),
                ('subject_id', models.BigIntegerField()),
                ('purpose', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('event_processing', 'Guest data for running an event'), ('marketing', 'Marketing')], max_length=32)),
                ('basis', models.CharField(choices=[('consent', 'Consent'), ('contract', 'Contract'), ('legitimate_interest', 'Legitimate interest'), ('legal_obligation', 'Legal obligation')], max_length=32)),
                ('policy_version', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event')),
            ],
            options={
                'db_table': 'privacy_consent_event',
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='privacy_con_subject_3333e7_idx')],
            },
        ),
    ]
