# Generated by Django 4.2.7 on 2026-08-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentevent',
            name='event',
        ),
        migrations.AddField(
            model_name='consentevent',
            name='event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
