# Generated by Django 4.2.7 on 2026-08-08 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privacy', '0002_remove_consentevent_event_consentevent_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_retention_days', models.PositiveIntegerField(default=35, help_text='Point-in-time backup / read-replica retention window, in days. Erasure clears the primary DB and CDN immediately, but backups keep the pre-erase copy until this many days pass — so this is the TRUE erasure SLA reported to data subjects. MUST match the actual RDS/PITR retention configured in infrastructure.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
                'db_table': 'privacy_settings',
            },
        ),
    ]
