# Generated by Django 4.2.7 on 2026-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0003_privacysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentevent',
            name='purpose',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('event_processing', 'Guest data for running an event'), ('marketing', 'Marketing'), ('age_confirmation', 'Confirmed minimum age at signup')], max_length=32),
        ),
    ]
