# Generated by Django 4.2.7 on 2026-08-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_expand_catalog_response_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
